-- Отмена разрешений для rl_employee
REVOKE EXECUTE ON PROCEDURE Room_Configuration_Insert FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Room_Configuration_Update FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Room_Configuration_Delete FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Room_Options_Insert FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Room_Options_Update FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Room_Options_Delete FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Reservation_Insert FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Reservation_Update FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Reservation_Delete FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Client_Insert FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Client_Update FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Client_Delete FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Client_Reservation_Insert FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Client_Reservation_Update FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Client_Reservation_Delete FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Add_Services_Reservation_Insert FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Add_Services_Reservation_Update FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Add_Services_Reservation_Delete FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Contract_Insert FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Contract_Update FROM rl_employee;
REVOKE EXECUTE ON PROCEDURE Contract_Delete FROM rl_employee;

-- Отмена разрешений для rl_administrator
REVOKE EXECUTE ON PROCEDURE Class_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Class_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Class_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Status_room_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Status_room_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Status_room_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Room_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Room_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Room_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Configuration_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Configuration_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Configuration_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Options_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Options_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Options_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Add_Services_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Add_Services_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Add_Services_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Employee_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Employee_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Employee_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Room_Configuration_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Room_Configuration_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Room_Configuration_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Room_Options_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Room_Options_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Room_Options_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Reservation_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Reservation_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Reservation_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Client_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Client_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Client_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Client_Reservation_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Client_Reservation_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Client_Reservation_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Add_Services_Reservation_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Add_Services_Reservation_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Add_Services_Reservation_Delete FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Contract_Insert FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Contract_Update FROM rl_administrator;
REVOKE EXECUTE ON PROCEDURE Contract_Delete FROM rl_administrator;

-- Отзыв прав для роли rl_Client
REVOKE SELECT ON Class FROM rl_Client;
REVOKE SELECT ON Status_Room FROM rl_Client;
REVOKE SELECT ON Room FROM rl_Client;
REVOKE SELECT ON Configuration FROM rl_Client;
REVOKE SELECT ON Room_Configuration FROM rl_Client;
REVOKE SELECT ON Options FROM rl_Client;
REVOKE SELECT ON Room_Options FROM rl_Client;
REVOKE SELECT ON Reservation FROM rl_Client;
REVOKE SELECT ON Client_Reservation FROM rl_Client;
REVOKE SELECT ON Add_Services FROM rl_Client;
REVOKE SELECT ON Add_Services_Reservation FROM rl_Client;
REVOKE SELECT ON Contract FROM rl_Client;

-- Отзыв прав для роли rl_Employee
REVOKE SELECT, INSERT, UPDATE ON Room_Configuration FROM rl_Employee;
REVOKE SELECT, INSERT, UPDATE ON Room_Options FROM rl_Employee;
REVOKE SELECT, INSERT, UPDATE ON Reservation FROM rl_Employee;
REVOKE SELECT, INSERT, UPDATE ON Client FROM rl_Employee;
REVOKE SELECT, INSERT, UPDATE ON Client_Reservation FROM rl_Employee;
REVOKE SELECT, INSERT, UPDATE ON Add_Services_Reservation FROM rl_Employee;
REVOKE SELECT, INSERT, UPDATE ON Contract FROM rl_Employee;
REVOKE SELECT ON Class FROM rl_Employee;
REVOKE SELECT ON Status_room FROM rl_Employee;
REVOKE SELECT ON Room FROM rl_Employee;
REVOKE SELECT ON Configuration FROM rl_Employee;
REVOKE SELECT ON Options FROM rl_Employee;
REVOKE SELECT ON Add_Services FROM rl_Employee;
REVOKE SELECT ON Employee FROM rl_Employee;

-- Отзыв прав для роли rl_Administrator
REVOKE SELECT, INSERT, UPDATE, DELETE ON Class FROM rl_Administrator;
REVOKE SELECT, INSERT, UPDATE, DELETE ON Status_room FROM rl_Administrator;
REVOKE SELECT, INSERT, UPDATE, DELETE ON Room FROM rl_Administrator;
REVOKE SELECT, INSERT, UPDATE, DELETE ON Configuration FROM rl_Administrator;
REVOKE SELECT, INSERT, UPDATE, DELETE ON Options FROM rl_Administrator;
REVOKE SELECT, INSERT, UPDATE, DELETE ON Add_Services FROM rl_Administrator;
REVOKE SELECT, INSERT, UPDATE, DELETE ON Employee FROM rl_Administrator;
REVOKE SELECT, DELETE ON Room_Configuration FROM rl_Administrator;
REVOKE SELECT, DELETE ON Room_Options FROM rl_Administrator;
REVOKE SELECT, DELETE ON Reservation FROM rl_Administrator;
REVOKE SELECT, DELETE ON Client FROM rl_Administrator;
REVOKE SELECT, DELETE ON Client_Reservation FROM rl_Administrator;
REVOKE SELECT, DELETE ON Add_Services_Reservation FROM rl_Administrator;
REVOKE SELECT, DELETE ON Contract FROM rl_Administrator;

-- Удаление индексов
DROP INDEX IF EXISTS Index_ID_Class;
DROP INDEX IF EXISTS Index_Name_Status_Room;
DROP INDEX IF EXISTS Index_ID_Status_Room;
DROP INDEX IF EXISTS Index_ID_Room;
DROP INDEX IF EXISTS Index_Number_Room;
DROP INDEX IF EXISTS Index_ID_Configuration;
DROP INDEX IF EXISTS Index_ID_Room_Configuration;
DROP INDEX IF EXISTS Index_ID_Options;
DROP INDEX IF EXISTS Index_ID_Room_Options;
DROP INDEX IF EXISTS Index_ID_Reservation;
DROP INDEX IF EXISTS Index_Number_Reservation;
DROP INDEX IF EXISTS Index_ID_Client;
DROP INDEX IF EXISTS index_surname_client;
DROP INDEX IF EXISTS index_name_client;
DROP INDEX IF EXISTS index_patronymic_client;
DROP INDEX IF EXISTS index_document_series_client;
DROP INDEX IF EXISTS index_document_number_client;
DROP INDEX IF EXISTS index_date_of_birth_client;
DROP INDEX IF EXISTS index_gender_client;
DROP INDEX IF EXISTS index_issued_by_client;
DROP INDEX IF EXISTS index_issued_date_client;
DROP INDEX IF EXISTS index_code_department_client;
DROP INDEX IF EXISTS Index_Phone_Client;
DROP INDEX IF EXISTS Index_Email_Client;
DROP INDEX IF EXISTS Index_Login_Client;
DROP INDEX IF EXISTS Index_ID_Client_Reservation;
DROP INDEX IF EXISTS Index_ID_Add_Services;
DROP INDEX IF EXISTS Index_ID_Add_Services_Reservation;
DROP INDEX IF EXISTS Index_ID_Employee;
DROP INDEX IF EXISTS Index_Login_Employee;
DROP INDEX IF EXISTS Index_ID_Contract;
DROP INDEX IF EXISTS Index_Number_Contract;

-- Удаление таблиц
DROP TABLE IF EXISTS Contract;
DROP TABLE IF EXISTS Add_Services_Reservation;
DROP TABLE IF EXISTS Client_Reservation;
DROP TABLE IF EXISTS Reservation;
DROP TABLE IF EXISTS Room_Options;
DROP TABLE IF EXISTS Options;
DROP TABLE IF EXISTS Room_Configuration;
DROP TABLE IF EXISTS Configuration;
DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS Status_Room;
DROP TABLE IF EXISTS Class;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Add_Services;
DROP TABLE IF EXISTS Employee;
